name: Node.js CI/CD - Rate Limiting Demo

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          echo " Tests à ajouter ici (exemple : npm test)"
          echo " Pour l'instant, on vérifie juste que le projet s'installe correctement."

      - name: Check build
        run: node -e "console.log(' Build OK');"
