name: Node.js CI/CD - Rate Limiting Demo

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rate-limiting-demo-main   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          echo " Tests à ajouter ici"
          echo " Installation et build réussis."

      - name: Check build
        run: |
          node -v
          npm -v
          echo " Le build CI/CD Node.js s'est exécuté correctement."
